# Generated by Django 6.0.3 on 2026-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finquery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='raw_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
